-- Local-only seed data.
--
-- Seeds run on `supabase db reset` (config.toml: [db.seed] enabled = true) but NOT on
-- `supabase db push`, so anything here stays local and never reaches cloud.
--
-- Vault secrets for the poll cron will be added here when the Last.fm engine is built.
