// Auto-generated by: supabase gen types typescript --local > lib/database.types.ts
// Regenerate after every schema change.

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string | null
          avatar_url: string | null
          created_at: string
        }
        Insert: {
          id: string
          username?: string | null
          avatar_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          username?: string | null
          avatar_url?: string | null
          created_at?: string
        }
        Relationships: []
      }
      spotify_accounts: {
        Row: {
          user_id: string
          provider_refresh_token: string | null
          access_token: string | null
          expires_at: string | null
          needs_reauth: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          user_id: string
          provider_refresh_token?: string | null
          access_token?: string | null
          expires_at?: string | null
          needs_reauth?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          user_id?: string
          provider_refresh_token?: string | null
          access_token?: string | null
          expires_at?: string | null
          needs_reauth?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
